name: FactionsPro
author: Tethered_, HostingItAll.com
description: A Plugin For Easily Managing Factions
version: 1.4.1
main: FactionsPro\FactionMain
api: [2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4]
commands:
  f:
    description: use /f help for all parameters
    permission: f.command
permissions:
  f.command:
    default: true
    description: "Allow use of all faction commands"
  fac.override:
    default: op
    description: "Allows op users to override factions"
